# Generated by Django 4.2.3 on 2023-08-04 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_alter_user_name_foodtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')])),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.IntegerField(choices=[('Vegetarian', 'Veg'), ('NonVegetarian', 'Non Veg'), ('Vegan', 'Vegan')])),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.user')),
            ],
        ),
        migrations.DeleteModel(
            name='FoodType',
        ),
        migrations.AddField(
            model_name='day',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.diet'),
        ),
        migrations.AddField(
            model_name='day',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.user'),
        ),
    ]
